pipeline:
  publish:
    group: publish
    image: plugins/docker
    repo: quay.io/tuannvm/gist-static-generator
    dockerfile: ./gist-static-generator/Dockerfile
    context: ./gist-static-generator/
    secrets:
      - docker_username
      - docker_password
      - docker_registry
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
