pipeline:
  publish:
    group: publish
    image: plugins/docker
    repo: quay.io/tuannvm/sample-app
    secrets:
      - docker_username
      - docker_password
      - docker_registry
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: [ tag ]
