---
- include: ssh.yml

- name: add neovim ppa
  apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install os dependancies
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes
    state: latest
    autoremove: yes
    autoclean: yes
  become: yes

- name: Download dein installer script
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: installer.sh
    mode: 0755
    
- shell: bash ~/installer.sh ~/.cache/dein

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/darwin/amd64/kubectl
    dest: /usr/local/bin/
    mode: 0755
  become: yes

- name: install helm
  block:
    - name: download helm
      get_url:
        url: https://storage.googleapis.com/kubernetes-helm/{{ helm_tgz }}
        dest: /tmp/
    - name: unarchive
      unarchive:
        copy: no
        src: /tmp/{{helm_tgz}}
        dest: /tmp
    - name: copy to bin
      copy:
        remote_src: yes
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin
        mode: 0755
      become: yes
  always:
    - name: cleanup...
      file:
        path: /tmp/linux-amd64
        state: absent

- name: Synchronize and delete files in dest.
  synchronize:
    src: "{{lookup('env', 'HOME')}}/.config/nvim"
    dest: "~/.config/"
    copy_links: yes
    delete: yes
    recursive: yes

- name: create home symlink
  file:
    dest: "{{lookup('env', 'MAC_PATH')}}"
    src: "~"
    state: link
    
- include: external.yml
