---
# defaults file for vps
apt_packages:
  - curl
  - neovim
  - tmux
  - nginx
  - mosh
  - net-tools
  - iproute2
  - iperf3
  - neovim
  - python-neovim
  - python3-neovim
  - python-pip
  - python3-pip
  - openvpn
  - golang
pip_packages:
  - neovim
kubectl_version: v1.10.5
helm_version: v2.8.2
dep_version: v0.5.0
helm_tgz: 'helm-{{ helm_version }}-linux-amd64.tar.gz'
terraform_version: 0.11.8
