alias tree="tree -L 1"
alias v="nvim"
alias vim="nvim"
alias emacs="/usr/local/bin/emacs"
alias vi="nvim"
alias chrome="open -a \"Google Chrome\""
alias tmux="tmux -u"
alias tf="terraform"
alias glog="git log --color --all --date-order --decorate --dirstat=lines,cumulative --stat | sed 's/\([0-9] file[s]\? .*)$\)/\1\n_______\n-------/g' | \less -R"
# syntax highlight with pygmentize
alias pygmentize="pygmentize -O style=native"
alias pcat="pygmentize"
