{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
  labels:
    {{- include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote  }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
  {{- if or (ne .Values.service.type "ClusterIP") (ne .Values.service.clusterIP "None") }}
      targetPort: 9300
  {{- end }}
      protocol: TCP
      name: keel
  selector:
    app: {{ template "fullname" . }}
  sessionAffinity: None
{{- end }}
